import Cart from './Cart/cart.js'
import Device from './Device/device.js'
// import Yamap from './Map/yamap.js'
import Ranger from './Ranger/ranger.min.js'
import UI from './Responsive interface/responsive_interface.js'