import Cart from './Cart/cart.js'
import Device from './Device/device.js'
import Yamap from './yaMap/yamap.js'
import Geography from './Geography/geography.js'
import Ranger from './Ranger/ranger.min.js'
import Payment from './Payment/payment.js'
import Contacts from './Contacts/contacts.js'
import Tooglers from './Togglers/index.js'
import UI from './Responsive interface/responsive_interface.js'